### ISSUE TITLE
2nd OKI MSM6295 chip not working in the Soldam core

### ISSUE THREAD

**Issue by ruiner9** [va7deo/MegaSys1_A#5] opened 2023-10-29 03:23 UTC
When running Soldam (latest version, 230923) the 2nd ADPCM channel is inactive. This can be easily verified by entering the soundtest and comparing the music to arcade captures or the OST rip on VGMrips.net. Sound test 03 (VS Mode music) uses both samplers, and turning off the OPM and ADPCM-0 chips in the OSD, leaving ADPSM-1 to play solo results in silence.

**Comment by atrac17** [comment] 2023-10-29 03:30
Will take a look, there seems to be some regressions. Currently bug hunting something else. Thanks!

**Comment by atrac17** [comment] 2024-01-06 20:07
Fixed in https://github.com/va7deo/MegaSys1_A/commit/cfa8f6874d73d850472552631ca5f55db72309e4

**Closed as completed by atrac17** 2024-01-06 20:07 UTC
